version: "3.7"

networks:
    ariakish-credit:
    shahrvand-mohajer-server_mamp-shared:
        external: true

services:
    # image project
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks: 
            - ariakish-credit
            - shahrvand-mohajer-server_mamp-shared
                
    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports: 
            - 9002:80
        volumes: 
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks: 
            - ariakish-credit
            - shahrvand-mohajer-server_mamp-shared


    # db mariadb
    mariadb:
        image: mariadb:latest
        restart: unless-stopped
        environment: 
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        ports: 
            - 3313:3306
        networks: 
            - ariakish-credit
            - shahrvand-mohajer-server_mamp-shared

      #Node Service
    nodejs:
        image: node:lts-alpine
        restart: unless-stopped
        tty: true
        volumes:
        - ./:/var/www
        networks:
            - ariakish-credit
  
    #PHPMYADMIN  Service
    phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      environment:
        - PMA_HOST=mariadb
        - PMA_USER=${DB_USERNAME}
        - PMA_PASSWORD=${DB_PASSWORD}
        - UPLOAD_LIMIT= 102400000000
      restart: always
      ports:
        - 9200:80
      networks:
        - ariakish-credit
        - shahrvand-mohajer-server_mamp-shared

