version: "3.7"
services:
    # image project
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks: 
            - ariakish
                
    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports: 
            - 8180:80
        volumes: 
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks: 
            - ariakish

    # db mariadb
    database:
        image: mariadb:latest
        restart: unless-stopped
        environment: 
            - MARIADB_DATABASE=${DB_DATABASE}
            - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
            - MARIADB_PASSWORD=${DB_PASSWORD}
            - MARIADB_USER=${DB_USERNAME}
        volumes: 
            - mariadb-data:/var/lib/mysql
        ports: 
            - 3388:3306
        command: --default-authentication-plugin=mysql_native_password
        networks: 
            - ariakish
  
    #PHPMYADMIN  Service
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        environment:
            - PMA_PASSWORD=${DB_PASSWORD}
            - PMA_USER=${DB_USERNAME}
            - PMA_HOST=${DB_HOST}
            - PMA_PORT=3388
            - UPLOAD_LIMIT=2G
            - MEMORY_LIMIT=2G
        restart: always
        ports:
            - 8115:80
        links:
            - database
        networks:
            - ariakish
volumes:
    mariadb-data:
        driver: local

networks:
    ariakish:
        driver: bridge