version: "3.7"
services:
    # image project
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks: 
            - ariakish
                
    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports: 
            - 8180:80
        volumes: 
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks: 
            - ariakish

    # db mariadb
    mariadb:
        image: mariadb:latest
        restart: unless-stopped
        environment: 
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes: 
            - mariadb-data:/var/lib/mysql
        ports: 
            - 3388:3306
        networks: 
            - ariakish
  
    #PHPMYADMIN  Service
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        environment:
            PMA_HOST: mariadb
            PMA_USER: ${DB_USERNAME}
            PMA_PASSWORD: secret
            UPLOAD_LIMIT:  102400000000
        restart: always
        ports:
            - 8115:80
        networks:
            - ariakish
volumes:
    mariadb-data:

networks:
    ariakish:
        driver: bridge